Repository studiometa/vue-mapbox-gl, pull requests merged in 2020-09, with the labels that each got.

#16 Feature/add missing props
  dist/VueMapboxGl.common.js
  dist/VueMapboxGl.common.js.map
  dist/VueMapboxGl.umd.js
  dist/VueMapboxGl.umd.js.map
  dist/VueMapboxGl.umd.min.js
  dist/VueMapboxGl.umd.min.js.map
  docs/components/MapboxMap.md
  docs/components/MapboxMarker.md
  docs/components/MapboxNavigationControl.md
  docs/components/MapboxPopup.md
  package.json
  src/components/MapboxMap.vue
  src/components/MapboxMarker.vue
  src/components/MapboxNavigationControl.vue
  src/components/MapboxPopup.vue
Labels: dependencies, enhancement

#17 Release/1.3.0
  .eslintrc.js
  .github/workflows/npm-publish.yml
  .github/workflows/tests.yml
  .prettierrc.js
  README.md
  babel.config.js
  dist/VueMapboxGl.common.js
  dist/VueMapboxGl.common.js.map
  dist/VueMapboxGl.umd.js
  dist/VueMapboxGl.umd.js.map
  dist/VueMapboxGl.umd.min.js
  dist/VueMapboxGl.umd.min.js.map
  docs/.vuepress/components/MapboxGeocoderDemo.vue
  docs/.vuepress/components/MapboxGeocoderDemoWithoutMap.vue
  docs/.vuepress/components/MapboxGeolocateControlDemo.vue
  docs/.vuepress/config.js
  docs/README.md
  docs/components/MapboxGeocoder.md
  docs/components/MapboxGeolocateControl.md
  docs/components/MapboxImage.md
  docs/components/MapboxMap.md
  docs/components/MapboxMarker.md
  docs/components/MapboxNavigationControl.md
  docs/components/MapboxPopup.md
  jest.config.js
  package-lock.json
  package.json
  src/components/MapboxGeocoder.vue
  src/components/MapboxGeolocateControl.vue
  src/components/MapboxImage.vue
  src/components/MapboxMap.vue
  src/components/MapboxMarker.vue
  src/components/MapboxNavigationControl.vue
  src/components/MapboxPopup.vue
  src/mixins/provide-inject-map.js
  src/utils/bind-events.js
  src/utils/bind-props.js
  tests/unit/.eslintrc.js
  tests/unit/.prettierrc.js
  tests/unit/bind-events.spec.js
  tests/unit/install.spec.js
  vue.config.js
Labels: release

#21 Hotfix/1.3.2
  dist/VueMapboxGl.common.js
  dist/VueMapboxGl.common.js.map
  dist/VueMapboxGl.umd.js
  dist/VueMapboxGl.umd.js.map
  dist/VueMapboxGl.umd.min.js
  dist/VueMapboxGl.umd.min.js.map
  package-lock.json
  package.json
  src/components/index.js
Labels: bug
